apiVersion: apps/v1
kind: Deployment
metadata:
  name: text-to-video-backend
  namespace: staging
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: text-to-video-backend
  template:
    metadata:
      labels:
        app: text-to-video-backend
        environment: staging
    spec:
      nodeSelector:
        environment: staging
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: text-to-video-backend
          image: nihapandu/text-to-video-backend:latest
          ports:
            - containerPort: 8000
          env:
            - name: ENV
              value: "staging"
            - name: MONGO_DB_URL
              value: MONGO_DB_URL=mongodb+srv://toheed:PK1smM7wkiApdSgh@pandu-cluster.9o0mewg.mongodb.net/
            - name: AWS_BUCKET_NAME
              value: "text-to-video-generation-staging"
            - name: DISTRIBUTION_DOMAIN_NAME
              value: https://cdn.pandu.ai/
            # - name: KAFKA_BROKER
            #   value: "kafka.default.svc.cluster.local:9092"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: KEY
            - name:  AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: SECRET
            - name: OPEN_AI_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-credentials
                  key: SECRET_KEY
            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe-credentials
                  key: SECRET_KEY
            - name: STRIPE_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe-credentials
                  key: PUBLIC_KEY
            - name: MATHPIX_APP_ID
              valueFrom:
                secretKeyRef:
                  name: mathpix-credentials
                  key: APP_ID
            - name: MATHPIX_APP_KEY
              valueFrom:
                secretKeyRef:
                  name: mathpix-credentials
                  key: APP_KEY
            - name: ELEVENLABS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: eleven-labs-credentials
                  key: SECRET_KEY
            - name: SERP_API_KEY
              valueFrom:
                secretKeyRef:
                  name: serpapi-credentials
                  key: API_KEY
            - name: STABILITY_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: stabilityai-credentials
                  key: SECRET
          volumeMounts:
            - name: assets-storage
              mountPath: /app/assets
        volumes:
          - name: assets-storage
            emptyDir: {}
            