apiVersion: apps/v1
kind: Deployment
metadata:
  name: text-to-video-backend
  namespace: staging
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: text-to-video-backend
  template:
    metadata:
      labels:
        app: text-to-video-backend
        environment: staging
    spec:
      nodeSelector:
        environment: staging
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: text-to-video-backend
          image: nihapandu/text-to-video-backend:latest
          ports:
            - containerPort: 8000
          env:
            - name: ENV
              value: "staging"
            - name: KAFKA_BROKER
              value: "kafka.default.svc.cluster.local:9092"