apiVersion: v1
kind: Service
metadata:
  name: text-to-video-backend
  namespace: staging
spec:
  type: LoadBalancer
  selector:
    app: text-to-video-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000