name: Text To Video Backend Staging

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: text-to-video-backend-staging
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      # - name: Extract Git Commit SHA
      #   id: extract_sha
      #   run: echo "SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      # - name: List Environment Variables
      #   run: printenv

      # - name: Log the Extracted SHA
      #   run: echo "Extracted SHA: ${{ env.SHA }}"

      - name: Build and push Docker image to DockerHub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/text-to-video-backend:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/text-to-video-backend:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region ${{ secrets.AWS_REGION }}

      - name: Update ECS service
        run: |
          aws eks update-kubeconfig --name pandu-production-cluster --region ${{ secrets.AWS_REGION }}
        
      - name: Apply Kubernetes Manifests (Staging)
        run: |
          kubectl apply -f k8s/staging/text-to-video-backend-deployment.yaml --namespace=staging
          kubectl apply -f k8s/staging/text-to-video-backend-service.yaml --namespace=staging

      - name: Update Deployment Image (Staging)
        run: |
          kubectl set image deployment/text-to-video-backend text-to-video-backend=${{ secrets.DOCKERHUB_USERNAME }}/text-to-video-backend:${{ github.sha }} --namespace=staging
          